//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.10.13 at 06:06:38 PM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.w3.org/1999/XSL/Format", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package es.uji.apps.fopreports.fop;
